src/bulk-actions-framework/main/default/objects/Bulk_Action_Configuration__mdt/Bulk_Action_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Metadata configuration for Bulk Action, UI properties, Execution Flows are set for a bulk action using this metadata</description>
    <label>Bulk Action Configuration</label>
    <pluralLabel>Bulk Action Configurations</pluralLabel>
</CustomObject>

src/bulk-actions-framework/main/default/objects/Bulk_Action_Configuration__mdt/fields/Action_Flow_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Action_Flow_API_Name__c</fullName>
    <description>This is the Action Flow, this flow consists of the core action for the bulk action. This flow is REQUIRED.</description>
    <inlineHelpText>This is the Action Flow, this flow consists of the core action for the bulk action. This flow is REQUIRED.</inlineHelpText>
    <label>Action Flow API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/bulk-actions-framework/main/default/objects/Bulk_Action_Configuration__mdt/fields/Custom_Success_Message__c.field-meta.xml
<CustomField>
    <fullName>Custom_Success_Message__c</fullName>
    <description>Message to be displayed on UI if action flow is executing in async mode</description>
    <inlineHelpText>Message to be displayed on UI if action flow is executing in async mode</inlineHelpText>
    <label>Custom Success Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/bulk-actions-framework/main/default/objects/Bulk_Action_Configuration__mdt/fields/Eval_Flow_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Eval_Flow_API_Name__c</fullName>
    <description>This is the evaluation flow, defines the logic for the filter criteria for selected records, bulk action is performed only on records meeting criteria. This criteria is defined in evaluation flow. This flow is OPTIONAL.</description>
    <inlineHelpText>This is the evaluation flow, defines the logic for the filter criteria for selected records, bulk action is performed only on records meeting criteria. This criteria is defined in evaluation flow. This flow is OPTIONAL.</inlineHelpText>
    <label>Eval Flow API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/bulk-actions-framework/main/default/objects/Bulk_Action_Configuration__mdt/fields/Eval_Flow_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Eval_Flow_Error_Message__c</fullName>
    <description>This is used to notify user output of the evaluation flow, this gives the reason why some of the records from selected records do not meet the eligibility criteria. Use summary of the criteria in evaluation flow to define this message.</description>
    <inlineHelpText>This is used to notify user output of the evaluation flow, this gives the reason why some of the records from selected records do not meet the eligibility criteria. Use summary of the criteria in evaluation flow to define this message.</inlineHelpText>
    <label>Eval Flow Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/bulk-actions-framework/main/default/objects/Bulk_Action_Configuration__mdt/fields/Input_Flow_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Input_Flow_API_Name__c</fullName>
    <description>This is the Input Flow, if bulk action needs any inputs from user, they are captured using input flow. This flow is OPTIONAL.</description>
    <inlineHelpText>This is the Input Flow, if bulk action needs any inputs from user, they are captured using input flow. This flow is OPTIONAL.</inlineHelpText>
    <label>Input Flow API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/bulk-actions-framework/main/default/objects/Bulk_Action_Configuration__mdt/fields/Is_Action_Flow_Execution_in_Async_Mode__c.field-meta.xml
<CustomField>
    <fullName>Is_Action_Flow_Execution_in_Async_Mode__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if action flow is executing in async mode</description>
    <inlineHelpText>Indicates if action flow is executing in async mode</inlineHelpText>
    <label>Is Action Flow Execution in Async Mode?</label>
    <type>Checkbox</type>
</CustomField>

src/bulk-actions-framework/main/default/objects/Bulk_Action_Configuration__mdt/fields/Preview_Screen_Button_Name__c.field-meta.xml
<CustomField>
    <fullName>Preview_Screen_Button_Name__c</fullName>
    <description>Button name on the preview screen, use the label representing next action, for example if your bulk action has input flow to capture task fields, name should be &apos;Enter Task Details&apos; or bulk action do not have input flow and only have action flow, label can be &apos;Create Tasks for selected cases&apos;</description>
    <inlineHelpText>Button name on the preview screen, use the label representing next action, for example if your bulk action has input flow to capture task fields, name should be &apos;Enter Task Details&apos; or bulk action do not have input flow and only have action flow, label can be &apos;Create Tasks for selected cases&apos;</inlineHelpText>
    <label>Preview Screen Button Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/bulk-actions-framework/main/default/objects/Bulk_Action_Configuration__mdt/fields/Preview_Screen_Field_Set_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Preview_Screen_Field_Set_API_Name__c</fullName>
    <description>API name of the field set used to show fields on the preview screen</description>
    <inlineHelpText>API name of the field set used to show fields on the preview screen</inlineHelpText>
    <label>Preview Screen Field Set API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/bulk-actions-framework/main/default/objects/Bulk_Action_Configuration__mdt/fields/Required_Permission__c.field-meta.xml
<CustomField>
    <fullName>Required_Permission__c</fullName>
    <description>This is the name of the custom permission, if user has this custom permission, clicking on bulk action button will show preview screen else user will get an error message.

If this field is blank, bulk action is available to all users.</description>
    <inlineHelpText>This is the name of the custom permission, if user has this custom permission, clicking on bulk action button will show preview screen else user will get an error message.

If this field is blank, bulk action is available to all users.</inlineHelpText>
    <label>Required Permission</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/bulk-actions-framework/main/default/classes/BulkActionUtil.cls
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @group: Util
 * @description: utility methods for Bulk Action Framework
 */
public with sharing class BulkActionUtil {
  @TestVisible
  private static final String INVALID_INPUT = 'Both `record` and `flowApiName` are required to call `Bulk Action Flows`';

  @TestVisible
  private static BulkActionUtil.Selector selector = new BulkActionUtil.Selector();
  @TestVisible
  private static InvocableAction invocableAction = new InvocableAction();

  /**
   * @description method to get configuration defined for selected bulk action,
   * configuration name is provided and config meta is returned
   * @param String, Bulk_Action_Configuration__mdt - developerName
   * @return Record, Bulk_Action_Configuration__mdt record matching developerName
   */
  public static Bulk_Action_Configuration__mdt getConfig(String configName) {
    List<Bulk_Action_Configuration__mdt> config = selector.getBulkActionTemplate(
      configName
    );
    return config.size() != 0 ? config[0] : null;
  }

  /**
   * @description method to get object prefixes for selected records
   * @param List<Id>, selected record id`s on which action to be performed
   * @return Set<String>, set of objects prefixes corrosponding to input records,
   * ideally this should be set with only single element
   */
  public static Set<String> getObjectsFromRecordIds(List<Id> recordIds) {
    Set<String> objectPrefixes = new Set<String>();
    for (Id recId : recordIds) {
      objectPrefixes.add(String.valueOf(recId).subString(0, 3));
    }
    return objectPrefixes;
  }

  public static List<Invocable.Action.Result> invokeBulkActionFlows(
    BulkActionTable table,
    String flowApiName,
    String flowType
  ) {
    return invokeBulkActionFlows(table, flowApiName, flowType, null);
  }

  public static List<Invocable.Action.Result> invokeBulkActionFlows(
    BulkActionTable table,
    String flowApiName,
    String flowType,
    Map<String, Object> screenFlowInputs
  ) {
    if (
      table?.rows == null ||
      (flowType == BulkActionConstants.FLOW_TYPE_ACTION &&
      flowApiName == null)
    ) {
      throw new IllegalArgumentException(INVALID_INPUT);
    }
    Map<Id, SObject> recordIdToRecordMap = BulkActionRecordDetailsFetcher.getFullyPopulatedRecord(
      table.objectName,
      table.selectedRecordIds
    );
    List<Map<String, Object>> interviewInputs = new List<Map<String, Object>>();
    for (BulkActionTable.Row row : table.rows) {
      Map<String, Object> inputs = new Map<String, Object>();
      inputs.put(
        BulkActionConstants.RECORD_VARIABLE,
        recordIdToRecordMap.get(row.displayRecord.Id)
      );
      if (screenFlowInputs != null && screenFlowInputs.keySet().size() > 0) {
        inputs.putAll(screenFlowInputs);
      }
      interviewInputs.add(inputs);
    }
    return invocableAction.invokeAction(flowApiName, interviewInputs);
  }

  @TestVisible
  public virtual class InvocableAction {
    public virtual List<Invocable.Action.Result> invokeAction(
      String flowApiName,
      List<Map<String, Object>> inputs
    ) {
      Invocable.Action action = Invocable.Action.createCustomAction(
        'Flow',
        flowApiName
      );
      action.setInvocations(inputs);
      return action.invoke();
    }
  }

  public static String getDataType(Object obj) {
    String varDataType = 'undefined';
    if (obj instanceof Integer) {
      varDataType = 'Integer';
    } else if (obj instanceof Double) {
      varDataType = 'Double';
    } else if (obj instanceof String) {
      varDataType = 'String';
    } else if (obj instanceof Blob) {
      varDataType = 'Blob';
    } else if (obj instanceof Boolean) {
      varDataType = 'Boolean';
    } else if (obj instanceof Date) {
      varDataType = 'Date';
    } else if (obj instanceof Datetime) {
      varDataType = 'DateTime';
    } else if (obj instanceof Decimal) {
      varDataType = 'Decimal';
    } else if (obj instanceof ID) {
      varDataType = 'Id';
    } else if (obj instanceof Long) {
      varDataType = 'Long';
    } else if (obj instanceof Time) {
      varDataType = 'Time';
    }
    return (varDataType);
  }

  @TestVisible
  private virtual inherited sharing class Selector {
    public virtual List<Bulk_Action_Configuration__mdt> getBulkActionTemplate(
      String configName
    ) {
      return [
        SELECT
          Custom_Success_Message__c,
          DeveloperName,
          MasterLabel,
          Action_Flow_API_Name__c,
          Eval_Flow_API_Name__c,
          Eval_Flow_Error_Message__c,
          Input_Flow_API_Name__c,
          Is_Action_Flow_Execution_in_Async_Mode__c,
          Preview_Screen_Button_Name__c,
          Preview_Screen_Field_Set_API_Name__c,
          Required_Permission__c
        FROM Bulk_Action_Configuration__mdt
        WHERE DeveloperName = :configName
        LIMIT 1
      ];
    }
  }
}